// <auto-generated />
using System;
using BrightPath.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BrightPath.Api.Data.Migrations
{
    [DbContext(typeof(BrightPathDbContext))]
    [Migration("20260927081810_ExclusionConstraints")]
    partial class ExclusionConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "btree_gist");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BrightPath.Api.Domain.Attendee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<string>("CancelledBy")
                        .HasColumnType("text")
                        .HasColumnName("cancelled_by");

                    b.Property<bool>("Chargeable")
                        .HasColumnType("boolean")
                        .HasColumnName("chargeable");

                    b.Property<bool>("LegacyViolation")
                        .HasColumnType("boolean")
                        .HasColumnName("legacy_violation");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.Property<string>("SourceLessonId")
                        .HasColumnType("text")
                        .HasColumnName("source_lesson_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uuid")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_attendees");

                    b.HasIndex("SourceLessonId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendees_source_lesson_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_attendees_student_id");

                    b.HasIndex("SessionId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("ix_attendees_session_id_student_id");

                    b.ToTable("attendees", null, t =>
                        {
                            t.HasCheckConstraint("ck_attendees_cancelled_by", "cancelled_by IS NULL OR cancelled_by IN ('family', 'tutor', 'centre')");

                            t.HasCheckConstraint("ck_attendees_cancelled_consistent", "(status = 'cancelled') = (cancelled_at IS NOT NULL)");

                            t.HasCheckConstraint("ck_attendees_status", "status IN ('booked', 'cancelled', 'no_show')");
                        });
                });

            modelBuilder.Entity("BrightPath.Api.Domain.BookingChange", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AfterCutoff")
                        .HasColumnType("boolean")
                        .HasColumnName("after_cutoff");

                    b.Property<Guid?>("AttendeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("attendee_id");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("ChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("changed_by");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_booking_changes");

                    b.HasIndex("AttendeeId")
                        .HasDatabaseName("ix_booking_changes_attendee_id");

                    b.HasIndex("SessionId", "ChangedAt")
                        .HasDatabaseName("ix_booking_changes_session_id_changed_at");

                    b.ToTable("booking_changes", null, t =>
                        {
                            t.HasCheckConstraint("ck_booking_changes_changed_by", "changed_by IS NULL OR changed_by IN ('family', 'tutor', 'centre')");

                            t.HasCheckConstraint("ck_booking_changes_kind", "kind IN ('created', 'cancelled', 'moved')");
                        });
                });

            modelBuilder.Entity("BrightPath.Api.Domain.Room", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_rooms");

                    b.ToTable("rooms", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "R1"
                        },
                        new
                        {
                            Id = "R2"
                        },
                        new
                        {
                            Id = "R3"
                        },
                        new
                        {
                            Id = "R4"
                        },
                        new
                        {
                            Id = "R5"
                        },
                        new
                        {
                            Id = "R6"
                        });
                });

            modelBuilder.Entity("BrightPath.Api.Domain.Session", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cancelled_at");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("LegacyViolation")
                        .HasColumnType("boolean")
                        .HasColumnName("legacy_violation");

                    b.Property<Guid?>("MovedToSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("moved_to_session_id");

                    b.Property<string>("RoomId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("room_id");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<string>("TutorId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tutor_id");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("MovedToSessionId")
                        .HasDatabaseName("ix_sessions_moved_to_session_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_sessions_room_id");

                    b.HasIndex("TutorId")
                        .HasDatabaseName("ix_sessions_tutor_id");

                    b.ToTable("sessions", null, t =>
                        {
                            t.HasCheckConstraint("ck_sessions_duration", "ends_at - starts_at IN (interval '60 minutes', interval '90 minutes')");
                        });
                });

            modelBuilder.Entity("BrightPath.Api.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_students_name");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("BrightPath.Api.Domain.Tutor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject");

                    b.HasKey("Id")
                        .HasName("pk_tutors");

                    b.ToTable("tutors", (string)null);
                });

            modelBuilder.Entity("BrightPath.Api.Domain.Attendee", b =>
                {
                    b.HasOne("BrightPath.Api.Domain.Session", "Session")
                        .WithMany("Attendees")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendees_sessions_session_id");

                    b.HasOne("BrightPath.Api.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_attendees_students_student_id");

                    b.Navigation("Session");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BrightPath.Api.Domain.BookingChange", b =>
                {
                    b.HasOne("BrightPath.Api.Domain.Attendee", null)
                        .WithMany()
                        .HasForeignKey("AttendeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_booking_changes_attendees_attendee_id");

                    b.HasOne("BrightPath.Api.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_booking_changes_sessions_session_id");
                });

            modelBuilder.Entity("BrightPath.Api.Domain.Session", b =>
                {
                    b.HasOne("BrightPath.Api.Domain.Session", null)
                        .WithMany()
                        .HasForeignKey("MovedToSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sessions_sessions_moved_to_session_id");

                    b.HasOne("BrightPath.Api.Domain.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_rooms_room_id");

                    b.HasOne("BrightPath.Api.Domain.Tutor", "Tutor")
                        .WithMany()
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_tutors_tutor_id");

                    b.Navigation("Room");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("BrightPath.Api.Domain.Session", b =>
                {
                    b.Navigation("Attendees");
                });
#pragma warning restore 612, 618
        }
    }
}
